accelerate launch --config_file configs/train/accelerate_config_zero2.yaml train.py \
  --data_root data/data \
  --meta_dir data/meta \
  --model_config_path configs/train/model.yaml \
  --height 480 \
  --width 864 \
  --num_frames 81 \
  --learning_rate 1e-4 \
  --num_epochs 5 \
  --remove_prefix_in_ckpt "pipe.model." \
  --output_path "./logs/train/sai_5B_lora" \